### ISSUE TITLE
passing a variable to the QUERY field

### ISSUE THREAD

**Issue by lverissimo** [eternity1984/node-red-contrib-trello-basis#3]
hi...
I was wondering if it is possible to pass a variable to the QUERY field, just like it is possible to pass a variable to the PATH field. 
For instance, I am trying to add a comment to a card. I need to insert such comment in the text field of the card in the QUERY field.
That would be great.
Thanks in advance.
Luis Verissimo

**Comment by eternity1984** [comment]
Hi @lverissimo, Thank you for your good

**Comment by eternity1984** [comment]
Hi @lverissimo, Thank you for your good

**Comment by eternity1984** [comment]
@lverissimo 
Hi, Thank you for your feedback :)
Can you give me some time to chew that over?

**Comment by eternity1984** [comment]
@lverissimo 
You can replace the **QUERY** field with the parameter of msg object if `msg.query` is set and contains a JSON.

![alt](https://user-images.githubusercontent.com/34591767/61165857-c611a780-a560-11e9-868b-ddf6421ee05e.png)

1. Add a Trello node to the workspace. Edit its properties and configure it as follows:
- **Method** field: `POST`
- **Path** field:  `/cards/{{idCard}}/actions/comments`
  - mustache are keyed from `complete msg object`
- **Query** field: `{}`

2. Add a Change node to the workspace.
Configure it to set `msg.idCard` to the **YOUR CARD ID**, `msg.query.text` to a **COMMENT**.
If you want to set an external parameter, you can also change it with field type.

> Add a new comment to a card
> https://developers.trello.com/reference#cardsidactionscomments

I plan to make it possible to use mustache syntax in the QUERY field in the future.
Best wishes

**Comment by eternity1984** [comment]
@lverissimo 
I would be grateful if you could try it again using pre-release package.

- [v0.3.1-a1](https://www.npmjs.com/package/node-red-contrib-trello-basis/v/0.3.1-a1)

`$ npm install node-red-contrib-trello-basis@0.3.1-a1`

**Changes**:
- Supported use mustache-syntax in the QUERY field.

> Attention:
> There is a downside that non-string parameters are converted to strings.

**Comment by eternity1984** [comment]
~~This feature is **deprecated**. NOT provided in ver 0.3.x.~~

It was released in [node-red-contrib-trello-basis@0.3.2](https://flows.nodered.org/node/node-red-contrib-trello-basis).

/close #3
