### ISSUE TITLE
Set dinamically 'Api Key' and 'Token' to 'trello-config'

### ISSUE THREAD

**Issue by diegoquirino** [eternity1984/node-red-contrib-trello-basis#4]
**Is there how to configure dinamically object trello-config, changing 'api key' and 'token' depending of the user is 'calling' endpoint in node-red server?**

*I know that it is not a bug, but you are the only who can path me to a clean solution...*

Thank you, very much.

**Comment by eternity1984** [comment]
@diegoquirino
Probably the easiest way is to have a separate node.
But, I know you don't want to create the same node.  Let me have a think about it.

Yu

**Comment by diegoquirino** [comment]
@eternity1984 
Thank you! I'll wait for updates or else final decision.

**Comment by eternity1984** [comment]
#5

**Comment by eternity1984** [comment]
@diegoquirino
Could you please test the beta version and let me know of any problems?

## Installation
Run the following command in your Node-RED user directory (typically ~/.node-red):
`$ npm install node-red-contrib-trello-basis@0.3.2-beta.1`

Or update package via palette manager. 

## Usage
Use `msg.trello_config` to dynamically change credentials.
![image](https://user-images.githubusercontent.com/34591767/66718799-0a903600-ee23-11e9-9a50-b9705b1df258.png)

You use either of the following two approaches:
1. Set `apikey` and `token` to dictionary
![image](https://user-images.githubusercontent.com/34591767/66719144-bc7d3180-ee26-11e9-990f-eceecdb2945c.png)

2. Set the TrelloConfigNode id
![image](https://user-images.githubusercontent.com/34591767/66719116-7b851d00-ee26-11e9-9d1d-ea1741e5f264.png)

If you use it, the following message is displayed:
<img src="https://user-images.githubusercontent.com/34591767/66719255-64472f00-ee28-11e9-88b2-ab2a5173612f.png" width="230px">


I hope to meet your requirements!! 😄

**Comment by diegoquirino** [comment]
@eternity1984 Thankfully for giving this clean solution to the problem.

But, with version 0.3.2-beta.1 I'm faced with another strange problem: "mustache" is not working in trello node.

This "mustached" JSON:

`
{
  "idList":"{{idList}}"
}
`

Is returning the problem **"Error: invalid value for idList"** because idList number is not being changed accordingly with variable same name... What could it be?

**Comment by diegoquirino** [comment]
Excuse me @eternity1984 , I didn't realize that "trello" nodes inputs changes from "msg.payload" to "complete msg object" because of updating to 0.3.2-beta.1

**Everything is working fine, very well, clean and concise.**

Thank you very much!

**Comment by eternity1984** [comment]
@diegoquirino
I appreciate your help :)

And I'm really sorry for the inconvenience caused.. 😭 
> But, with version 0.3.2-beta.1 I'm faced with another strange problem: "mustache" is not working in trello node.

The mustache support for the QUERY field was alpha released, but **this feature has a downside that non-string parameters are converted to strings**.  I did not understand what many people wanted, so I decided not to provide #3.

**Comment by diegoquirino** [comment]
In my opinion, You should maintain _mustache replace_. To me, for example, it was very helpfull and I could easily overcome "problem of all be a string in the end" in all cases that I work with number or dates, without any trauma.

So, now, how could I perform POST requests to trello without of the use of "mustaches" to queries?

**Comment by eternity1984** [comment]
@diegoquirino
Wow, I really wanted to hear such an opinion!! Give me a few hours to get to it.

You can override the configuration by passing `msg.query` to the Trello node :)

1. Add a `Change` node or `Function` node to the workspace.
2. Configure it as follows: `msg.query.idList = msg.idList`
3. Wire it before the trello node.

**Comment by eternity1984** [comment]
@diegoquirino, I will release it shortly.😄

**Comment by diegoquirino** [comment]
Thank you, very much! I'll wait for updates!

**Comment by eternity1984** [comment]
@diegoquirino You can now update package via palette manager 👍 
Please try it again ;)

[node-red-contrib-trello-basis@0.3.2](https://flows.nodered.org/node/node-red-contrib-trello-basis)

**Comment by diegoquirino** [comment]
Thank you, very much @eternity1984,

Everything is working fine now, good job! 😄 👍
