### ISSUE TITLE
No output from node

### ISSUE THREAD

**Issue by matiya** [eternity1984/node-red-contrib-trello-basis#9]
Hi! Out of all the trello nodes for node red, I believe yours is the one with the most flexibility.

The problem is that I can't get it to work. I can see the requests are made, but nothing is coming out from the output of the node, just the payload.id that I set up in the inject node.

Do you think may be trello changed its api in the last months?

**Comment by matiya** [comment]
I'm sorry but this wasn't an issue with your node.

I don't know why, but I copied the flow from one tab to the other and suddenly it was working.

I guess is an issue with node-red itself.

**Comment by eternity1984** [comment]
@matiya Thanks for your interest to this node!  I'm glad to hear it works!
If you faced any problem, please feel free to open issues🤗
